#! /bin/sh
# vim: ft=sh


main() {
    local repo_root="$(dirname "$0")/.."
    cd "$repo_root" || exit 1

    local slideshows_dir="slideshows" 
    local output_index_file="index.html"

    cd "$slideshows_dir" \
        || exit 1

    links="$(find -mindepth 1 -maxdepth 1 -type d \
        -printf "<p><a href=$slideshows_dir/%P/index.html>%P</a></p>\n"
    )" || exit 1

    cd - || exit 1

    printf "\
<!doctype html>
<!-
This file really should not be here, but in slideshows/. However, GitHub
Pages has its limitations
-->
<body>
$links
</body>
" > "$output_index_file"

    echo Rebuilt "$output_index_file"
}

main "$@"
